### ISSUE TITLE
Services not starting up post deployment

### ISSUE THREAD

**Issue by jithendra-trisys** [egovernments/Digit-Core#24]
Hi Team, 

We have successfully deployed the Digit platform version 2.4 (pgr) without any errors on the AWS Kubernetes cluster which we have created using the document guide from the docs.digit.org website. 

After deploying we could note that most of the services int he egov name space are not in a running state and screenshot of the same is posted below. 

![Screenshot 2022-04-22 at 11 20 23 AM](https://user-images.githubusercontent.com/21379038/164612460-0e5cf0a4-3dee-49dd-850e-90295f88eb4e.png)

Request your help in getting the services up and running.

**Comment by nikesh-eGov** [comment]
As we had discussed over the chat, check digit deploy [doc](https://docs.digit.org/setup/install-on-cloud#2.-deploy-digit) and follow the instruction for forking and creating a new GitHub user to initiate gitSync.

**Comment by gajendran-egov** [comment]
This issue is fixed, the updated installation steps would address this issue.
